# Generated by Django 6.0.2 on 2026-02-25 05:49

import jobs.models.case
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_case_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='unique_key',
            field=models.CharField(default=jobs.models.case.generate_unique_key, max_length=8, unique=True),
        ),
    ]
